"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "../../../lib/supabase";

type Attempt={id:string;score:number|null;passed:boolean|null;submitted_at:string|null;user_id:string;exam_id:string};
export default function Grading(){const [attempts,setAttempts]=useState<Attempt[]>([]),[selected,setSelected]=useState<Attempt|null>(null),[examAnswers,setExamAnswers]=useState<any[]>([]),[score,setScore]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
useEffect(()=>{async function load(){if(!supabase){setMessage("Supabase 未配置");setLoading(false);return}const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage("请先登录管理员账号");setLoading(false);return}const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(!p||!["admin","manager"].includes(p.role)){setMessage("只有管理员或管理者可以批改考试");setLoading(false);return}const {data,error}=await supabase.from("exam_attempts").select("*").order("submitted_at",{ascending:false});if(error)setMessage(error.message);else setAttempts((data||[]) as Attempt[]);setLoading(false)}load()},[]);
async function openAttempt(a:Attempt){setSelected(a);setScore(a.score==null?"":String(a.score));setMessage("");if(supabase){const {data}=await supabase.from("exam_answers").select("id,question_id,answer,is_correct").eq("attempt_id",a.id);setExamAnswers(data||[])}}async function save(){if(!selected||!supabase)return;const value=Number(score);if(!Number.isFinite(value)){setMessage("请输入有效分数");return}const {error}=await supabase.from("exam_attempts").update({score:value,passed:value>=60}).eq("id",selected.id);if(error)setMessage(error.message);else{setAttempts(attempts.map(x=>x.id===selected.id?{...x,score:value,status:"graded"}:x));setMessage("评分已保存");}}
return <main><header><Link href="/" className="brand">✦ CrossBorder <b>Academy</b></Link><nav><Link href="/learning">学习中心</Link><Link href="/exams">考试中心</Link></nav></header><section className="content"><p className="eyebrow">ADMIN GRADING</p><h1>考试批改</h1><p className="lead">查看考试提交记录，并录入简答题和实操题的人工评分。</p>{loading?<p>正在加载提交记录…</p>:message&&attempts.length===0?<p className="auth-message">{message}</p>:<div style={{display:"grid",gap:16,maxWidth:820}}>{attempts.length===0?<div className="exam-card"><p>目前还没有考试提交记录。学生提交考试后会显示在这里。</p></div>:attempts.map(a=><div key={a.id} className="exam-card" style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16}}><div><b>提交记录</b><p style={{color:"#68716c"}}>{a.submitted_at?new Date(a.submitted_at).toLocaleString():"时间未知"} · 状态：{a.passed==null?"待批改":a.passed?"已通过":"未通过"} · 当前分数：{a.score??"未评分"}</p></div><button className="cta" onClick={()=>openAttempt(a)}>批改</button></div>)}</div>}{selected&&<div className="exam-card" style={{marginTop:24,maxWidth:520}}><h2>录入最终成绩</h2><p>请结合简答题、实操题及截图完成人工评分。</p><div style={{display:"grid",gap:14,margin:"18px 0"}}>{examAnswers.map(a=><div key={a.id} style={{padding:14,border:"1px solid #e5ded2",borderRadius:10}}><b>题目 {a.question_id}</b>{String(a.answer||"").startsWith("data:image")?<img src={a.answer} alt="实操截图" style={{display:"block",maxWidth:"100%",maxHeight:360,marginTop:10,borderRadius:8}}/>:<p style={{whiteSpace:"pre-wrap",marginTop:8}}>{a.answer||"未作答"}</p>}</div>)}</div><input value={score} onChange={e=>setScore(e.target.value)} type="number" min="0" placeholder="最终总分" style={{width:"100%",padding:"12px",border:"1px solid #d8d2c7",borderRadius:8}}/><button className="cta" onClick={save} style={{marginTop:12}}>保存并发布成绩</button></div>}</section></main>}